package PDV.views.janelas;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import pdv.entities.Cliente;
import pdv.entities.Venda;
import pdv.enums.CadastroVenda;
import pdv.enums.FormaPagamento;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author barce
 */
public class JanelaCadastroVenda extends javax.swing.JDialog {

    private CadastroVenda cadastroVenda;
    private Venda venda;
    private boolean confirmado;
    private DefaultComboBoxModel<FormaPagamento> DefaultComboBoxModel;

    public boolean operacaoConfirmada() {
        return confirmado;
    }

    public static boolean executar(CadastroVenda cadastroVenda, Venda venda) {
        JanelaCadastroVenda janelaVenda = new JanelaCadastroVenda(null, cadastroVenda, venda);

        janelaVenda.setLocationRelativeTo(null);
        janelaVenda.setVisible(true);
        return janelaVenda.operacaoConfirmada();
    }

    /**
     * Creates new form JanelaCadastroProduto
     */
    public JanelaCadastroVenda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JanelaCadastroVenda(java.awt.Frame parent, CadastroVenda cadastroVenda, Venda venda) {
        super(parent, true);
        confirmado = false;
        this.cadastroVenda = cadastroVenda;
        this.venda = venda;

        initComponents();


        if (cadastroVenda == CadastroVenda.alterar || cadastroVenda == cadastroVenda.consultar) {
            int codVenda = venda.getIdVenda();
            edCodVenda.setText(Integer.toString(codVenda));

            Date dataHora = venda.getDataHora();
            SimpleDateFormat formatoSaida = new SimpleDateFormat("dd/MM/yyyy");
            String dataFormatada = formatoSaida.format(dataHora);
            edDataHora.setText(dataFormatada);
            edDataHora.setText("");

            BigDecimal valorTotal = venda.getValorTotal();
            edValorTotal.setText(valorTotal.toString());

            Cliente idCliente = venda.getIdCliente();
            edIdCliente.setText(String.valueOf(idCliente));

        }

        botaoCancelar.setVisible(cadastroVenda != cadastroVenda.consultar);
        edCodVenda.setEnabled(cadastroVenda != cadastroVenda.consultar);
        edDataHora.setEnabled(cadastroVenda != cadastroVenda.consultar);
        edValorTotal.setEnabled(cadastroVenda != cadastroVenda.consultar);
       jComboBoxPG.setEnabled(cadastroVenda != cadastroVenda.consultar);
        edIdCliente.setEnabled(cadastroVenda != cadastroVenda.consultar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCodProd = new javax.swing.JLabel();
        labelPrecoProd = new javax.swing.JLabel();
        labelNomeProd = new javax.swing.JLabel();
        edDataHora = new javax.swing.JTextField();
        edIdCliente = new javax.swing.JTextField();
        edValorTotal = new javax.swing.JTextField();
        labelCadastroProduto = new javax.swing.JLabel();
        botaoOk = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edCodVenda = new javax.swing.JTextField();
        labelFormaPagamento = new javax.swing.JLabel();
        jComboBoxPG = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelCodProd.setText("Data e Hora:");

        labelPrecoProd.setText("Id Cliente:");

        labelNomeProd.setText("Valor Total da Venda:");

        edDataHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edDataHoraActionPerformed(evt);
            }
        });

        edIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edIdClienteActionPerformed(evt);
            }
        });

        labelCadastroProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCadastroProduto.setText("Cadastrar Venda");

        botaoOk.setText("OK");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Código da venda:");

        edCodVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCodVendaActionPerformed(evt);
            }
        });

        labelFormaPagamento.setText("Forma de Pagamento:");

        jComboBoxPG.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(labelFormaPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(edDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(labelNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(edValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(edIdCliente))
                    .addComponent(edCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelCadastroProduto)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodProd)
                    .addComponent(edDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNomeProd)
                    .addComponent(edValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecoProd)
                    .addComponent(edIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFormaPagamento)
                    .addComponent(jComboBoxPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoOk)
                    .addComponent(botaoCancelar))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edDataHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edDataHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edDataHoraActionPerformed

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
        if (cadastroVenda != cadastroVenda.consultar) {
            String codVendaTexto = edCodVenda.getText();
            int codVenda = Integer.parseInt(codVendaTexto);
            venda.setIdVenda(codVenda);

            String dataHoraTexto = edDataHora.getText();
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date dataHoraUtil = formatoEntrada.parse(dataHoraTexto);
                java.sql.Date dataHoraSQL = new java.sql.Date(dataHoraUtil.getTime());
                venda.setDataHora(dataHoraSQL);

            } catch (ParseException e) {
                System.err.println("Ocorreu um erro ao converter a data. Certifique-se de inserir a data no formato dd/MM/yyyy.");
            }

            String valorTotalTexto = edValorTotal.getText();
            BigDecimal valorTotal = new BigDecimal(valorTotalTexto);
            venda.setValorTotal(valorTotal);

            String clienteIdTexto = edIdCliente.getText();
            int idCliente = Integer.parseInt(clienteIdTexto);
            Cliente cliente = new Cliente(); // Cria uma nova instância de Cliente com o ID convertido
            venda.setIdCliente(cliente);

            String formaPagamentoSelecionada = (String) jComboBoxPG.getSelectedItem();
            if (formaPagamentoSelecionada != null) {
                FormaPagamento formaPagamentoEnum = FormaPagamento.valueOf(formaPagamentoSelecionada);
                venda.setFormaPagamento(formaPagamentoEnum);
            } else {

            }

            dispose();
        }
    }//GEN-LAST:event_botaoOkActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void edCodVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCodVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodVendaActionPerformed

    private void edIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edIdClienteActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCadastroVenda.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaCadastroVenda dialog = new JanelaCadastroVenda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoOk;
    private javax.swing.JTextField edCodVenda;
    private javax.swing.JTextField edDataHora;
    private javax.swing.JTextField edIdCliente;
    private javax.swing.JTextField edValorTotal;
    private javax.swing.JComboBox jComboBoxPG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCadastroProduto;
    private javax.swing.JLabel labelCodProd;
    private javax.swing.JLabel labelFormaPagamento;
    private javax.swing.JLabel labelNomeProd;
    private javax.swing.JLabel labelPrecoProd;
    // End of variables declaration//GEN-END:variables
}
